### PR TITLE
rewrite exporter and improve performances 

### LINKED ISSUE #45: auth token not being refreshed, thus causing refresh token expired errors
We're running an issue on 0.8.0 where after some time, the cf exporter will fail to pull many results from cloud foundry. In the logs, this always seems to be the issue:

```
time="2019-08-30T20:50:40Z" level=info msg="Starting cf_exporter (version=0.8.0, branch=master, revision=bf26f42d3e08c1278e056558a09546f885874808)" source="cf_exporter.go:135"
time="2019-08-30T20:50:40Z" level=info msg="Build context (go=go1.11.5, user=root@ca9c8a45a760, date=20190209-02:47:21)" source="cf_exporter.go:136"
time="2019-08-30T20:50:40Z" level=info msg="Listening on :9134" source="cf_exporter.go:239"
time="2019-09-13T22:50:39Z" level=error msg="Error while listing service instances: Error requesting service instances: Get https://api.system.<truncated>.com/v2/service_instances?: oauth2: cannot fetch token: 401 Unauthorized\nResponse: {\"error\":\"invalid_token\",\"error_description\":\"Invalid refresh token expired at Fri Sep 13 20:50:40 UTC 2019\"}" source="service_instances_collector.go:142"
```

This seems to happen with 6 different cloud foundry deployments, consistently. It looks very similar to issues https://github.com/bosh-prometheus/cf_exporter/issues/12 and https://github.com/bosh-prometheus/cf_exporter/issues/1 although those are quite old and outdated issues.

Looking at the latest diff from 0.8.0, don't think upgrading will help from our end.

Restarting always seems to resolve it. We also had seen similar issues with the bosh/firehose exporters _once_, but we had believe that that may have been due to an unrelated issue (although it could still be related: only problem is they are still running just fine right now so can't really confirm/deny/etc).

### LINKED ISSUE #46: Support CC API V3
CC V2 API is deprecating following CC API V3, see related [deprecation plan](https://docs.google.com/document/d/1KFZogeeexOqFf13oKHloe2QAorLh9OqwQHp8JvBl9lY/edit) and [cf-dev@ thread](https://lists.cloudfoundry.org/g/cf-dev/topic/29809681#8528) 

Seems the go-cfclient does not yet supports V3 APIs, see https://github.com/cloudfoundry-community/go-cfclient/issues/151

CF CLI has extracted V3 api cli at https://github.com/cloudfoundry/cli/tree/master/api/cloudcontroller/ccv3 might be make it easier than in the past to reuse CF CLI codebase

Similar work migrating to CF CLI client lib done in https://github.com/cloudfoundry-community/terraform-provider-cf/pull/203 by @ArthurHlt is expected to ease migration to V3, see https://github.com/cloudfoundry-community/terraform-provider-cf/issues/120

### PR DESCRIPTION
**Pull request by psycofdj**
This pull request contains an almost backward compatible rewrite of the exporter.

### CF API Bindings

This implementation replaces https://github.com/cloudfoundry-community/go-cfclient by
https://github.com/cloudfoundry/cli (`v8.4.0`) API bindings. Which also migrates from deprecated
`/v2` to `/v3` API endpoints.

Because the `v3` API lacks an efficient way to query informations about running app instances, this
implementation still use the `/v2/space/<guid>/summary` endpoint.

### Chores

Bump all dependencies and fixes minor CVE:
- `Docker Engine before 1.6.1 allows local users to set arbitrary Linux Security Modules (LSM) and docker_t policies via an image that allows volumes to override files in /proc.`
- `Libcontainer and Docker Engine before 1.6.1 opens the file-descriptor passed to the pid-1 process before performing the chroot, which allows local users to gain privileges via a symlink attack in an image.`

### Metric changes

| metric name                             | change                                                     |
| -                                       | -                                                          |
| metrics.namespace_service_binding_info  | now shows bindings of type key (not bound to any apps)     |
| metrics.namespace_service_instance_info | now shows user-provided service instances                  |
| metrics.namespace_events_info           | now shows more type of events, like task creation          |

### Querying strategy

In order to get data as fresh as possible, this implementations keeps the original just-in-time
querying strategy. However, the following changes improve the overall querying times:
- objects required by multiple metrics are queried only once
- objects are queried with a far bigger "per_page" parameter, reducing the number of requests needed
  to walk the pagination
- space summaries are fetched directly for each space (avoiding API calls to get org-to-space relationship)

### Performances

The following measurements were taken on one of my production platforms (>2500 apps, >800 spaces)

| Active Filter     | now    | before  |
| -----             | ------ | ------- |
| All               | 47s    | 143s    |
| Applications      | 32s    | 89s     |
| Buidpacks         | 0.3s   | 0.1s    |
| Events            | 3s     | 1s      |
| IsolationSegments | 0.3s   | 0.1s    |
| Organizations     | 1.5s   | 1.3s    |
| Routes            | 7s     | 10s     |
| SecurityGroups    | 1s     | 32s     |
| ServiceBindings   | 12s    | 122s    |
| ServiceInstances  | 6s     | 12s     |
| ServicePlans      | 0.4s   | 0.8s    |
| Services          | 0.8s   | 0.9s    |
| Spaces            | 4s     | 4s      |
| Stacks            | 0.1s   | 0.5s    |

:information_source: 
- timings fluctuate quite a bit between measurements and heavily depends on CF's internal database load. 
- this still gives an idea about the effect of the PR

### Packaging

This PR includes a refactoring of the repository packaging system:
- replaces [promu](https://github.com/prometheus/promu) by [goreleaser](https://github.com/goreleaser/goreleaser)
  -  :warning: release windows packages are now shipped as `zip` files only (instead of `zip` and `tgz` files)
- replaces [travis](https://www.travis-ci.com/) to [github-actions](https://docs.github.com/en/actions)
  - :warning: this requires to configure `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` secrets on the repository in order to push docker images to https://hub.docker.com/u/boshprometheus
  - :warning: to cut and publish a new release: just tag the repository with `vX.Y.Z`
- setup's dependabot workflow

### Flag Changes 

| before | now | description |
| - | - | - |
| `--cf.api-v3-enabled` | *removed* | the exporter only use V3 API |
| `--events.query` | *removed* | the exporter always query last 10 minutes with 5k events per page |
| `--log.level="info"` | `--log.level="error"` |  log level now defaults to `error` |
| `--log.format="logger:stderr"` | *removed* |   |
|  | `log.stream="stderr"` | set output stream for log  |
|  | `log.json` | output logs with JSON format  |
| | `--collector.workers=10` | configure concurrent workers for API queries |

### Issues

- fixes #46 
- fixes #45 (a new token is issued for each scrap)
- will probably improve #49 even if it sill does just-in-time queries

### CODE REVIEW

**Comment by benjaminguttmann-avtq** [comment]
Hi @psycofdj 

first of all thanks for that huge work. Not sure if it is really possible to review 3k file changes but I will try to get an overview and provide some feedback.

**Comment by Kmmel** [comment]
one thing I do not like about this PR is that parts that could have been easily put in a dedicated PR are also packed into this one, e.g. the whole packaging adjustments. I can understand that all of this has been done all in one, but it just adds more topics into this one PR. 
Also it might helps in the future to have commits that bundle changes logically somehow. So that it is at least possible to review the PR commit by commit which would reduce the number of files changed to review each time drastically.

**Comment by benjaminguttmann-avtq** [comment]
one thing I do not like about this PR is that parts that could have been easily put in a dedicated PR are also packed into this one, e.g. the whole packaging adjustments. I can understand that all of this has been done all in one, but it just adds more topics into this one PR.
Also it might helps in the future to have commits that bundle changes logically somehow. So that it is at least possible to review the PR commit by commit which would reduce the number of files changed to review each time drastically.

**Comment by psycofdj** [comment]
You are right. I can rewrite history with 4 or 5 different commits if you wish.

**Comment by benjaminguttmann-avtq** [comment]
Hi, if that is not too big of an issue that would really help I think

**Comment by psycofdj** [comment]
ok give me an hour or so and I will force push

**Comment by psycofdj** [comment]
here you are @benjaminguttmann-avtq, I hope this will be easier to review 
at least, most of file changes are bundled in the `vendor dependency` 30f239a commit

**Comment by lrstanley** [comment]
Also curious if there is a reason for still having a `vendors` folder which clobbers diffs? Given the improvements to go modules, as well as the Golang package proxy, feel like it's no longer needed.

**Comment by psycofdj** [comment]
> Also curious if there is a reason for still having a `vendors` folder which clobbers diffs? Given the improvements to go modules, as well as the Golang package proxy, feel like it's no longer needed.

this helps compiling in air-gapped environments

**Comment by lrstanley** [comment]
> > Also curious if there is a reason for still having a `vendors` folder which clobbers diffs? Given the improvements to go modules, as well as the Golang package proxy, feel like it's no longer needed.
> 
> this helps compiling in air-gapped environments

Still seems unnecessary. E.g. these things can be pulled in when creating the release for bosh, so they're available during compile time, and don't need to be stored in the repo. For other cases where it's being compiled elsewhere (not via bosh release), that same issue would be occur for any other Go package, and thus should be handled on an as-needed basis (e.g. artifact mirror), or simply pulling an already compiled version.

The fact that it completely mangles diffs for any change, also makes it extremely difficult to vet the code and related changes.

**Comment by psycofdj** [comment]
@benjaminguttmann-avtq any news about this PR ?

**Review by benjaminguttmann-avtq — APPROVED** [review]

**Comment by risicle** [comment]
Is this going to be merged? Because if it is, I'll have to do a bit of rebasing & adaptation of my PR #56. But I won't do that until I know this is in.

**Comment by benjaminguttmann-avtq** [comment]
@risicle I think @psycofdj will be happy to help you/ be willing to improve what has been done inside this PR to make it more understandable

**Comment by risicle** [comment]
Something that's particularly unclear is why _some_ resources have been used directly from `code.cloudfoundry.org/cli/resources` but some have been given their own definitions in `models`. I'm sure there's a reason, but there's no explanation of the rationale and which approach a new resource should take.

Why does the mutex live on a fetcher when multiple fetchers need to cooperate on populating the same `CFObjects` (`entry`? `result`?) at the same time?

What is the division of responsibilities between a collector, fetcher and worker? If I have to do aggregation on my fetched resources, where should that be done?

Again, I'm sure there's reasoning, but it's nice for a contributor if they don't have to perform a day's worth of detective work to discover each of these.

**Comment by psycofdj** [comment]
@risicle sorry I missed the question

**Q. Why some objects `code.cloudfoundry.org/cli/resources` objects are overwritten in `models` ?**

The cf-cli team worked hard refactoring the cli code to make it usable as client bindings. However some objects still lack of proper unserialization and some fields available in the api response are dropped. In an effort to avoid to use a completely different code-base (like https://github.com/cloudfoundry-community/go-cfclient which had big v3 compatibility problems in the past), the approach here consisted in overriding only the few problematic resources 

**Q. Why does the mutex live on a fetcher ?**

I'm not sure to understand your question here. 3 thoughts:

- The propose of the mutex is protect the writing of `SpaceSummaries` and `AppSummaries` fields of the result object. Those map writes can occur in parallel when multiple goroutines are ran to fetch space details. https://github.com/bosh-prometheus/cf_exporter/blob/84d748e357e87d3d85b0e4978eb1275130d39a00/fetcher/fetcher_handlers.go#L49-L64
- A single `CFObjects` is populated by a single `fetcher` instance. This instance spawns and handles the live-cycle of multiple goroutines to fetch api data and write result in the fetcher object. 
- I totally agree that is kinda misleading. The mutex could make one think that the `Fetcher.GetObjects` function is reentrant but it is not. Parallel `GetObjects` sould be ran on different `Fetcher` instances. In the context of `cf_exporter`, this is not a big deal since every `/metrics` requests spawns its own `Fetcher` and calls `Fetcher.GetObjects` only once.

**Q. What is the division of responsibilities between a collector, fetcher and worker?**

* `Fetcher`: return a "god object" containing all need data. It role is to query the cf api in the most efficient way.
* `Collector`: read the god object and write metrics. Its divided in several optional collectors (buildpacks, routes, stacks.. etc). The main `Collector` object handle the activation or deactivation of desired collectors according to input configuration. 
* `Worker`: only an internal tool used by Fetcher. It handles the pool of goroutine that will execute stacked jobs. `Push` adds a job, `Do` executes the goroutines, `Wait` wait until all jobs are done.
* `Filter`: represent what modules are activated or deactivated. That is only syntax sugar to make readable what should have been many `if` in the rest of the code.

**Comment by risicle** [comment]
Ok thanks a lot for this, I think it confirms most of my guesses and with luck someone else will find this information useful.

**Pull request merged**
