### PR TITLE
Add support for exporting Events from events API

### PR DESCRIPTION
**Pull request by DRuggeri**
Addition to add scraping from [Events API](https://apidocs.cloudfoundry.org/223/events/list_all_events.html).

### CODE REVIEW

**Comment by DRuggeri** [comment]
My best guess for why the build failed is the `/` in the feature branch name...
```
>> building docker image
invalid argument "boshprometheus/cf-exporter:feature/events-collector" for t: invalid reference format
See 'docker build --help'.
make: *** [docker] Error 125
```

The software itself builds, tests and functions fine in go. The docker build also succeeds, too.

**Comment by DRuggeri** [comment]
Hi, there @frodenas... any interest to incorporate this or is there feedback needed? Very interested in seeing this capability.

**Comment by DRuggeri** [comment]
Hi, all... just checking in again. I'd very much like to see this incorporated into the codebase. How can I help make that happen?

**Comment by frodenas** [comment]
@DRuggeri Apologies for the late reply. Adding an events collector is something that has been discussed previously (see https://github.com/bosh-prometheus/cf_exporter/issues/20). There was a time where we used to have one but limited to applications events, and we had to remove it (see  https://github.com/bosh-prometheus/cf_exporter/commit/71922c528a1c5cfc12c8c113c48b655ce5c39242) because it was completelly unusable on medium-large environments.

I like the approach taken in this PR by using a filter by timestamp to not fetch all events, but I'm still concerned about:
* The stress on the CC by using the query;
* The cardinality of the `events_info` metric series, where we have 10 labels per metric (`type`, `actor`, `actor_type`, `actor_name`, `actor_username`, `actee`, `actee_type`, `actee_name`, `space_id`, `organization_id`) with a high variance, will have unexpected side effects (see this [blog post](https://blog.freshtracks.io/bomb-squad-automatic-detection-and-suppression-of-prometheus-cardinality-explosions-62ca8e02fa32) for more details).

Is there a particular use case you want to solve?

**Comment by DRuggeri** [comment]
Hi, @frodenas;
I agree that having state in the collector is far from ideal, but as you've pointed out, is the only usable way to keep from killing the CC (that I could dream up, at least). Perhaps an acceptable compromise would be to disable this collector by default and add an `events.query` command line parameter that can be used to [filter requests on the CC API side](https://apidocs.cloudfoundry.org/223/events/list_all_events.html)? Another potential mitigation, if all of these metrics are important to an org, is to use a read-only CC as the target of queries.

To the second question, yes, we have a few metrics that are specific use cases we'd like to satisfy. They can be boiled down to things along the lines of:
- Dashboarding the number of self-service actions performed (to demonstrate value of the platform versus traditionally managed IT)
- Identify statistics around audit-related actions (a user performed X activity Y times)
- Find trends around crashing apps
- Identify platform hotspots (busy orgs/spaces)

The cardinality explosion problem is not something I had considered, but is a valid concern. I'm wondering if 'default disable' and similar filtering to what is mentioned above could be a solution? Perhaps split the types of events into their own metric (`events_crash_info`, `events_app_start_info`, `events_service_update`, etc)?

**Comment by DRuggeri** [comment]
OK - I'll update this to disable the events collector by default as well as add the query. While I'm in the neighborhood, what do you think about making the fields of the vector a configurable parameter as well? For those that really want to tighten down the metrics returned and achieve scale, this could be a valuable capability.

**Comment by DRuggeri** [comment]
I've modified the collectors to disable Events by default and added the query.

**Comment by frodenas** [comment]
@DRuggeri can you please rebase against master? there're some conflicts that prevent merging the PR. Thanks.

**Comment by DRuggeri** [comment]
Sure - sorry for not noticing that having crept in this weekend.

This is done. Took a second attempt after an error crept into the first try, but it looks clean at this point.

**Comment by frodenas** [comment]
Thanks @DRuggeri

**Pull request merged**
